### ISSUE TITLE
시작화면 TETRIS의 'S'자 출력 밀림 오류 발견

### ISSUE THREAD

**Issue by sujin22** [sujin22/OSS_Tetris_Team3#12]
![image](https://user-images.githubusercontent.com/37799862/40577173-283a7564-613c-11e8-954d-d3341f7e4300.png)

**Comment by sujin22** [comment]
![image](https://user-images.githubusercontent.com/37799862/40577252-8a2eb838-613d-11e8-9813-b31bc8afe5a3.png)
수정 완료했고 브랜치 푸시합니다.
병합 동의해주세요

**Comment by sojin16** [comment]
동의합니다!

**Comment by ds1mbp5720** [comment]
아주 보기좋군요 거슬렸습니다. 동의

**Comment by Junuu** [comment]
동의합니다~

**Comment by MinSeok95** [comment]
동의합니다.
